### ISSUE TITLE
series ev

### ISSUE THREAD

**Issue by derpierre65** [RefreshingWater/DDABuilds#19]
for the new series ev hero i need some images (i can temporarily use the olds from dundefplanner):

- hero (512x512) -> assets/images/heroes/series_ev.png
- tower icons -> assets/images/tower/tower_name.png
- tower map icons in all possible DU sizes (e.g. 1 DU = 90x35, 2 DU = 110x35...) -> assets/images/tower/tower_name_DU.png (buff_beam_1.png)

**Comment by RefreshingWater** [comment]
Commited Images: 
1201ab465de12cc534063c9b3d1bb07cdf28b8d7
8ac5f1b0156342c49047525bcc0eb9d8e22250da
6dda876dbfbbbbb50171e6e6bceff5ad2e765833
