### ISSUE TITLE
Can not deactivate "AFK Able" and "Hardcore"

### ISSUE THREAD

**Issue by Chakratos** [RefreshingWater/DDABuilds#20]
If AFK Able or Hardcore is enabled you cannot deactivate it by unticking the checkbox

Is related to: string to bool conversion. "false" == true

See: https://github.com/RefreshingWater/DDABuilds/tree/bugfix/ISSUE-20_hardcore_and_afkable_fix
for fix

**Comment by Chakratos** [comment]
Just now saw that this also is fixed on dev, my bad. You can safely delete my branch then.

**Comment by derpierre65** [comment]
is fixed in the current pull request
