### ISSUE TITLE
build list url changed

### ISSUE THREAD

**Issue by derpierre65** [RefreshingWater/DDABuilds#39]
i have changed the build list url (last time that was changed), now the filter parameter for gamemode was renamed to gameMode and the base url is `/builds/...` instead of `index.php?build-list&...`  

example old: `/index.php?build-list&gamemode=Survival&difficulty=Nightmare....`  
example new: `/builds/?gameMode=Survival&difficulty=Nightmare`  

Should be changed in the future (any version), a fix for the old url is already in the current pull request and make the old urls compatible with the new system

**Comment by RefreshingWater** [comment]
Updated DDA to support the new build list URL. Should be in the next public build that gets sent out.
